{
 "title": "KrakenD OTEL",
 "description": "Example of collected OTEL metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "query": "1m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(krakend_pipe_duration_count,url_path)"
    }
   },
   { "name": "max_list", "query": "3,5,10,15,20" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests",
     "type": "stat",
     "description": "Incoming HTTP Requests",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Throughtput",
     "type": "stat",
     "description": "Average requests per second over the time range",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max_over_time(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range])-min_over_time(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range]))/ $__range_s",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "stat",
     "description": "The Average Response Time",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_sum{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range])) / (sum(rate(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range]))+0.0001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Proxy Requests",
     "type": "stat",
     "description": "Processed Proxy Requests",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(krakend_pipe_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Requests",
     "type": "stat",
     "description": "Started Backend Requests",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(krakend_backend_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency  p99",
     "type": "stat",
     "description": "Percentile 99 of HTTP server latency.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_bucket{instance=~\"$instance\",url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency  p95",
     "type": "stat",
     "description": "Percentile 95 of HTTP server latency.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_bucket{instance=~\"$instance\",url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency  p90",
     "type": "stat",
     "description": "Percentile 90 of HTTP server latency.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(http_server_duration_bucket{instance=~\"$instance\",url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency  p75",
     "type": "stat",
     "description": "Percentile 75 of HTTP server latency.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_duration_bucket{instance=~\"$instance\",url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency  p50",
     "type": "stat",
     "description": "Percentile 50 of HTTP server latency.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_bucket{instance=~\"$instance\",url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "Numer of request per second received",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval]))",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Latencies (Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (delta(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (delta(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (delta(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (delta(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (delta(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Data Sent",
     "type": "timeseries",
     "description": "Number of bytes sent in the body responses",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_response_size_sum{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval]))",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Average Response Size",
     "type": "timeseries",
     "description": "Average response size",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_response_size_sum{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval]) / rate(http_server_response_size_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Response Status Codes Distribution",
     "type": "piechart",
     "description": "Pie chart of status codes.",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(http_response_status_code) (delta(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipe Stage Duration 99p",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipe Stage Duration 95p",
     "type": "stat",
     "description": "The Pipe Stage Duration 95p",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipe Stage Duration 90p",
     "type": "stat",
     "description": "The Pipe Stage Duration 90p",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by(le) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipe Stage Duration 75p",
     "type": "stat",
     "description": "The Pipe Stage Duration 75p",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipe Stage Duration 50p",
     "type": "stat",
     "description": "The Pipe Stage Duration 50p",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Stage Duration 99p",
     "type": "stat",
     "description": "The Backend Stage Duration 99p",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(krakend_backend_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Stage Duration 95p",
     "type": "stat",
     "description": "The Backend Stage Duration 95p",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(krakend_backend_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Stage Duration 90p",
     "type": "stat",
     "description": "The Backend Stage Duration 90p",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(krakend_backend_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Stage Duration 75p",
     "type": "stat",
     "description": "The Backend Stage Duration 75p",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(krakend_backend_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Stage Duration 50p",
     "type": "stat",
     "description": "The Backend Stage Duration 50p",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(krakend_backend_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "Numer of request per second received",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "95p Endpoint Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, url_path, http_request_method) (rate(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Data Sent",
     "type": "timeseries",
     "description": "Number of bytes sent in the body responses",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(http_server_response_size_sum{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Data Sent",
     "type": "table",
     "description": "Total amount of data sent per endpoint",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, histogram_quantile(0.95, sum by (le, url_path) (rate(http_server_response_size_bucket{instance=~\"$instance\"}[$__range])))) >= 0",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Average Response Size",
     "type": "timeseries",
     "description": "Average response size per endpoint",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(http_server_response_size_sum{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval]) / rate(http_server_response_size_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Fastests p95 endpoints",
     "type": "table",
     "description": "Response times fastests p95",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "bottomk($max_list, histogram_quantile(0.95, sum by (le, url_path) (rate(http_server_duration_bucket{instance=~\"$instance\", url_path!=\"\"}[$__range])))) >= 0",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Slowest p95 endpoints",
     "type": "table",
     "description": "Response times slowest p95",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, url_path) (rate(http_server_duration_bucket{instance=~\"$instance\", url_path!=\"\"}[$__range])))) >= 0",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Response Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(http_response_status_code) (delta(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(http_response_status_code) (delta(http_server_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency Heat Map",
     "type": "heatmap",
     "description": "The latency heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(increase(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__interval])) by (le)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Size Heat Map",
     "type": "heatmap",
     "description": "The Response Size Heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(increase(http_server_response_size_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__interval])) by (le)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "Numer of request per second received",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(krakend_pipe_duration_count{instance=~\"$instance\", url_path=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "95p Endpoint Latencies",
     "type": "timeseries",
     "description": "The Pipe Endpoint p95 Latencies",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, url_path, http_request_method) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Fastests p95 endpoints",
     "type": "table",
     "description": "Response times fastests p95",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "bottomk($max_list, histogram_quantile(0.95, sum by (le, url_path) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__range])))) >= 0",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Slowest p95 endpoints",
     "type": "table",
     "description": "Response times slowest p95",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, url_path) (rate(http_server_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\", url_path!=\"\"}[$__range])))) >= 0",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Latency Heat Map",
     "type": "heatmap",
     "description": "The latency heatmap",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__interval])) by (le)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "95p pipe duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, url_path) (rate(krakend_pipe_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "Number of BACKEND request per second executed",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 179 },
     "targets": [
      {
       "expr": "rate(http_client_duration_count{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "95p Backend Request Duration",
     "type": "timeseries",
     "description": "Time it takes for a request to have the firsta byte of the response body ready to be readed.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 179 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, url_path, http_request_method) (rate(http_client_duration_bucket{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Received Content Length",
     "type": "timeseries",
     "description": "Number of bytes reported by consumed responses Content-Length values. In case of chunked responses, the metrics are not displayed here.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(http_client_response_size_sum{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "No Content Length",
     "type": "timeseries",
     "description": "Number ",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(http_client_response_no_content_length_total{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Average Content Length",
     "type": "timeseries",
     "description": "Average response content-lenght. Chunked responses are not taken into account.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(http_client_response_size_sum{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval]) / rate(http_client_response_size_count{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Read Content Size",
     "type": "timeseries",
     "description": "Number of bytes readed from the body. In case a cancel, or a closed connection, the read bytes might not match those of content-lenght. This metric includes chunked responses that do not come with the Content-Length header set.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(http_client_request_read_size_hist_sum{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Avg Read Content Size",
     "type": "timeseries",
     "description": "Average Number of bytes readed from the body. In case a cancel, or a closed connection, the read bytes might not match those of content-lenght. This metric includes chunked responses that do not come with the Content-Length header set.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(http_client_request_read_size_hist_sum{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval]) / rate(http_client_request_read_size_hist_count{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$interval])",
       "legendFormat": "{{http_request_method}} {{url_path}}"
      }
     ]
    },
    {
     "title": "Fastests p95 endpoints",
     "type": "table",
     "description": "Backend Response times fastests p95",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "bottomk($max_list, histogram_quantile(0.95, sum by (le, url_path) (rate(http_client_duration_bucket{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\", url_path!=\"\"}[$__range])))) >= 0",
       "legendFormat": "{{url_path}}"
      }
     ]
    },
    {
     "title": "Slowest p95 endpoints",
     "type": "table",
     "description": "Response times slowest p95",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, url_path) (rate(http_client_duration_bucket{instance=~\"$instance\", krakend_endopoint=~\"$endpoint\", url_path!=\"\"}[$__range])))) >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(http_response_status_code) (delta(http_client_duration_count{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(http_response_status_code) (delta(http_client_duration_count{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency Heat Map",
     "type": "heatmap",
     "description": "The BACKEND requests latency heatmap",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 231 },
     "targets": [
      {
       "expr": "sum(increase(http_client_duration_bucket{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$__interval])) by (le)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Size Heat Map",
     "type": "heatmap",
     "description": "The Response Size Heatmap",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 231 },
     "targets": [
      {
       "expr": "sum(increase(http_client_response_size_bucket{instance=~\"$instance\", krakend_endpoint=~\"$endpoint\"}[$__interval])) by (le)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed and Timed out",
     "type": "timeseries",
     "description": "Failed and timed out requests.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 244 },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_failed_count_total{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(rate(http_client_requests_timedout_count_total{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "Timed out"
      }
     ]
    },
    {
     "title": "Started vs Canceled",
     "type": "timeseries",
     "description": "Requests started vs canceled.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 244 },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_started_count_total{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "Started"
      },
      {
       "expr": "sum(rate(http_client_requests_canceled_count_total{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval]))",
       "legendFormat": "Cancelled"
      }
     ]
    },
    {
     "title": "Requests Details p95",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_get_conn_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "Get Conn"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_dns_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "DNS"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_tls_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "TLS"
      }
     ]
    },
    {
     "title": "95p requests duration",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 264 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, url_path, server_address) (rate(http_client_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "{{http_request_method}} {{server_address}}{{url_path}}"
      }
     ]
    },
    {
     "title": "95p backend duration",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 275 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, url_path) (rate(krakend_backend_duration_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests Started",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 288 },
     "targets": [
      {
       "expr": " sum by (http_request_method_original, krakend_endpoint, server_address, url_path) (rate(http_client_requests_started_count_total{instance=~\"$instance\", url_path=~\"$endpoint\"}[1m]))",
       "legendFormat": "{{http_request_method_original}} {{server_address}}{{url_path}}"
      }
     ]
    },
    {
     "title": "Response Size p95",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_response_size_bucket{instance=~\"$instance\", url_path=~\"$endpoint\"}[$__rate_interval])))",
       "legendFormat": "Response Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Panel",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "filters": [
        {
         "id": "2adf4ac6",
         "operator": "=~",
         "scope": "span",
         "tag": "url.path",
         "value": [ "$endpoint" ],
         "valueType": "string"
        },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [],
         "valueType": "string"
        },
        {
         "id": "span-name",
         "operator": "=~",
         "scope": "span",
         "tag": "name",
         "value": [],
         "valueType": "string"
        }
       ],
       "limit": 10,
       "spss": 100,
       "tableType": "traces"
      }
     ]
    }
   ]
  }
 ]
}